KSDGControllerApp/KSDGControllerApp/Models/GuestMessage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace KSDGControllerApp.Models
{
    public partial class GuestMessage
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public DateTime DatePosted { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string FilePath { get; set; }
    }
}

KSDGControllerApp/KSDGControllerApp/Models/GuestMessageMetadata.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KSDGControllerApp.Models
{
    [MetadataType(typeof(GuestMessageMD))]
    public partial class GuestMessage
    {
        public class GuestMessageMD
        {
            [Display(Name = "名稱")]
            [Required]
            public string Name { get; set; }
            [Display(Name = "貼文日期")]            
            public DateTime DatePosted { get; set; }
            [Display(Name = "Email")]
            [Required]
            [EmailAddress]
            public string Email { get; set; }
            [Display(Name = "主題")]
            [Required]
            public string Subject { get; set; }
            [Display(Name = "內文")]
            [Required]
            public string Body { get; set; }
            [Display(Name = "檔案路徑")]
            public string FilePath { get; set; }
        }
    }
}

KSDGControllerApp/KSDGControllerApp/Controllers/Ex01Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KSDGControllerApp.Controllers
{
    public class Ex01Controller : Controller
    {
        // GET: Ex01
        public ActionResult Index()
        {
            return View();
        }
    }
}

KSDGControllerApp/KSDGControllerApp/Controllers/GuestController.cs
using KSDGControllerApp.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KSDGControllerApp.Controllers
{
    public class GuestController : Controller
    {
        // GET: Guest
        public ActionResult Index()
        {
            // query database.
            using (var context = new GuestMessageDbContext())
            {
                var query = context.GuestMessages.OrderByDescending(m => m.DatePosted);
                return View(query.ToList());
            }
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(GuestMessage Msg)
        {
            if (!this.ModelState.IsValid)
                return View();

            var files = Request.Files;

            if (files.Count > 0)
            {
                string fileStorePath = Server.MapPath(VirtualPathUtility.ToAbsolute("~/files"));
                string fileName = DateTime.Now.Ticks.ToString() + Path.GetExtension(files[0].FileName);
                files[0].SaveAs(fileStorePath + "/" + fileName);
                Msg.FilePath = "~/files/" + fileName;
            }

            // write to database.
            using (var context = new GuestMessageDbContext())
            {
                context.GuestMessages.Add(Msg);
                context.SaveChanges();
            }

            return Redirect("Index");
        }

        public ActionResult Download(string Id = null)
        {
            if (string.IsNullOrEmpty(Id))
                return HttpNotFound();

            string filename = null;

            using (var context = new GuestMessageDbContext())
            {
                var query = context.GuestMessages.Where(m => m.Id == new Guid(Id));
                if (!query.Any())
                    return HttpNotFound();
                else
                    filename = query.First().FilePath;
            }

            string fileStorePath = Server.MapPath(VirtualPathUtility.ToAbsolute(filename));
            FileStream fs = new FileStream(fileStorePath, FileMode.Open, FileAccess.Read);
            return new FileStreamResult(fs, 
                string.Format("content-disposition; attachment={0}", Path.GetFileName(fileStorePath)));
        }
    }
}

KSDGControllerApp/KSDGControllerApp/Views/Guest/Add.cshtml
@model KSDGControllerApp.Models.GuestMessage

@{
    Layout = "~/Views/Shared/_Bootstrap.cshtml";
}

<div class="row">
    &nbsp;
</div>
<div class="row">
    <div class="col-md-8">

        @using (Html.BeginForm("Add", "Guest", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>留言板</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FilePath, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="GuestPostFile" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("返回列表", "Index")
        </div>
    </div>
</div>

KSDGControllerApp/KSDGControllerApp/Views/Guest/Index.cshtml
@model IEnumerable<KSDGControllerApp.Models.GuestMessage>

@{
    Layout = "~/Views/Shared/_Bootstrap.cshtml";
}

<div class="row">
    &nbsp;
</div>
<div class="row">
    <div class="col-md-8">
        <h2 class="page-header">訪客留言板</h2>
        <p>
            @Html.ActionLink("Create New", "Add", routeValues: null, htmlAttributes: new { @class = "btn btn-default", role = "button" })
        </p>
        <section class="comment-list">
            <!-- First Comment -->
            @foreach (var item in Model)
            {
                <article class="row">
                    <div class="col-md-10 col-sm-10">
                        <div class="panel panel-default arrow left">
                            <div class="panel-body">
                                <header class="text-left">
                                    <h3>@item.Subject</h3>
                                </header>
                                <div class="comment-post">
                                    <p>
                                        @item.Body
                                    </p>
                                </div>
                                <footer class="text-right">
                                    <div><a href="@Url.Action("Download", "Guest", new { Id = @item.Id })"><i class="fa fa-download"></i>@Path.GetFileName(item.FilePath)</a></div>
                                    <div class="comment-user"><i class="fa fa-user"></i>@item.Name</div>
                                    <time class="comment-date" datetime="@item.DatePosted"><i class="fa fa-clock-o"></i>@item.DatePosted.ToString("yyyy/MM/dd HH:mm:ss")</time>
                                </footer>
                            </div>
                        </div>
                    </div>
                </article>
            }
        </section>
    </div>
</div>

KSDGControllerApp/KSDGControllerApp/Views/Shared/_Bootstrap.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">留言板範例程式</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">首頁</a></li>
                    <li><a href="#about">關於</a></li>
                    <li><a href="#contact">聯絡我</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div><!-- /.container -->
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>